[build]
  base = "nextjs-base"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Fallback for SPA-like behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200