[build]
  base = "nextjs-base"
  command = "pnpm install --no-frozen-lockfile && pnpm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200